SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE wp_arsenal_teams;

-- Основные 53 команды Беларуси
INSERT INTO wp_arsenal_teams (id,name,code,country_code,country_name,logo_url,flashscore_id,founded_year,venue_name,venue_address,venue_city,venue_capacity,is_arsenal) VALUES 
(1, 'Гомель', NULL, 'BY', 'Belarus', '', '6379', NULL, '', '', '', NULL, 0),
(2, 'Торпедо-БЕЛАЗ', NULL, 'BY', 'Belarus', '', '7123', NULL, '', '', '', NULL, 0),
(3, 'Минск', NULL, 'BY', 'Belarus', '', '6378', NULL, '', '', '', NULL, 0),
(4, 'Нафтан-Новополоцк', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(5, 'Неман', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(6, 'Витебск', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(7, 'Днепр', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(8, 'Брест', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(9, 'Волна', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(10, 'Замок', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(11, 'Витязь', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(12, 'Сокол', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(13, 'Металлист', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(14, 'Речица', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(15, 'Полоцк', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(16, 'Пинск', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(17, 'Мозырь', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(18, 'Светлогорск', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(19, 'Лида', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(20, 'Волковыск', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(21, 'Вилейка', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(22, 'Новогрудок', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(23, 'Слуцк', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(24, 'Ошмяны', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(25, 'Рогачёв', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(26, 'Гродно', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(27, 'Могилёв', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(28, 'Гомельская область', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(29, 'Витебская область', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(30, 'Минская область', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(31, 'Гродненская область', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(32, 'Могилёвская область', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(33, 'Брестская область', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(34, 'Юношеская сборная', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(35, 'Резервная сборная', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(36, 'Благовещина', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(37, 'Наваполоцк', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(38, 'Жодино', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(39, 'Климовичи', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(40, 'Чаусы', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(41, 'Копыль', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(42, 'Раков', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(43, 'Кричев', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(44, 'Рассоха', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(45, 'Косово', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(46, 'Октябрьский', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(47, 'Сестрорецк', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(48, 'Гранёво', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(49, 'Синий камень', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(50, 'Белый город', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(51, 'Красный восток', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(52, 'Голубой берег', NULL, 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 0),
(53, 'Арсенал Дзержинск', 'ARSN', 'BY', 'Belarus', '', '', NULL, '', '', '', NULL, 1);

SET FOREIGN_KEY_CHECKS = 1;
